---
### global settings
base_path: "/home/{{ ansible_user }}/poa-bridge"
nodejs_deb_url: "https://deb.nodesource.com/setup_8.x"

### parity service
parity_bin_url: "https://d1h4xl4cr1h0mo.cloudfront.net/v1.9.2/x86_64-unknown-linux-gnu/parity"
parity_bin_sha256: "3604a030388cd2c22ebe687787413522106c697610426e09b3c5da4fe70bbd33"

### parity home side configs
home_name: "home"
home_bootnodes: ""

### parity foreign side configs
foreign_name: "foreign"
foreign_bootnodes: ""

### bridge service
#bridge_bin_url: "https://transfer.sh/3B7sR/bridge"
#bridge_bin_sha256: "eb538b395b4e25e74a0d6a059183000a218b2732b1a2f5812772ab9c6d6ed2ea"
bridge_bin_url: "https://transfer.sh/NfYCM/bridge"
bridge_bin_sha256: "a72e266e7d510c93ff582c74fd8cb7e29d03e1ab2f6ff19d6f57544cc9be11d8"

### bridge config
#bridge_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/bridge/contracts/bridge.sol"
#token_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/bridge/token/BridgeableToken.sol"
bridge_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge/poa-dev-2/contracts/bridge.sol"
token_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge/poa-dev-2/contracts/BridgeableToken.sol"

estimated_gas_cost_of_withdraw: 0

home_contract_name: "HomeBridge"
foreign_contract_name: "ForeignBridge"

home_deploy_gas: 3000000
home_deploy_gas_price: 18000000000
foreign_deploy_gas: 3000000
foreign_gas_price: 18000000000
deposit_relay_gas: 1200000
deposit_repay_gas_price: 18000000000
withdraw_confirm_gas: 3000000
withdraw_gas_price: 18000000000
withdraw_relay_gas: 3000000
withdraw_relay_gas_price: 18000000000

### initial deployment
solc_bin_url: "https://github.com/ethereum/solidity/releases/download/v0.4.20/solc-static-linux"
solc_bin_sha256: "d966b8215a4f83377ce9d622c9198fe91e5b93300652bf081aaf2f6aa3ac6a16"

### bridge_ui
install_bridge_ui: no
bridge_db_toml: "{{ base_path }}/bridge/db.toml"
bridge_ui_repo: "https://github.com/poanetwork/bridge-ui"
bridge_ui_branch: "bridgeble_token"
