- name: Check if remote computer is listening standard ssh port
  wait_for: port="22" state="started" host="{{ inventory_hostname }}" connect_timeout="5" timeout="10" delegate_to="localhost" ignore_errors="yes"
  register: port_used

- name: Set inventory ansible_port to default
  set_fact: ansible_port="22"
  when: port_used.state == "started"

- name: Setup new SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ custom_ssh_port }}"
  when: ansible_port != custom_ssh_port
  notify: restart sshd
  
- name: Preconf - run handlers immediately
  meta: flush_handlers

- name: Change ansible port for
  set_fact: ansible_port="{{ custom_ssh_port }}"