---
# - name: Preconf.Syslog forward
#   become: yes
#   become_user: root
#   when: syslog_server_port != ""
#   block:
#     - name: Preconf.Syslog forward - add line to /etc/rsyslog.conf
#       lineinfile:
#         path: /etc/rsyslog.conf
#         insertbefore: '^\$IncludeConfig'
#         line: "*.* @@{{ syslog_server_port }}"
#       notify: restart rsyslog

- name: Preconf.Syslog forward
  become: yes
  become_user: root
  when: syslog_server_port != ""
  block:
    - name: Preconf.Syslog forward - add lines to /etc/rsyslog.conf
      blockinfile:
        path: /etc/rsyslog.conf
        insertbefore: '^\$IncludeConfig'
        content: |
          $ActionResumeInterval 10
          $ActionQueueSize 100000
          $ActionQueueDiscardMark 97500
          $ActionQueueHighWaterMark 80000
          $ActionQueueType LinkedList
          $ActionQueueFileName syslogqueue
          $ActionQueueCheckpointInterval 100
          $ActionQueueMaxDiskSpace 2g
          $ActionResumeRetryCount -1
          $ActionQueueSaveOnShutdown on
          $ActionQueueTimeoutEnqueue 2
          $ActionQueueDiscardSeverity 0
          *.* @@{{ syslog_server_port }}
      notify: restart rsyslog
