# to verify ufw configuration run:
# sudo ufw status verbose

---
- name: UFW
  become: yes
  become_user: root
  block:
    - name: Preconf.UFW - install ufw
      package:
        name: ufw
        state: present

    - name: Preconf.UFW - clean old rules
      ufw:
        state: reset

    - name: Preconf.UFW - configure defaults
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      with_items:
        - direction: "incoming"
          policy: "deny"
        - direction: "outgoing"
          policy: "allow"

    - name: Preconf.UFW - allow ssh access
      ufw:
        rule: "allow"
        port: "{{ ansible_port|default(22) }}"
        proto: "tcp"

    - name: Preconf.UFW - disable logging
      ufw:
        logging: off

    - name: Preconf.UFW - enable ufw to start on boot
      ufw:
        state: enabled
      notify:
        - restart ufw
