---
- name: "Bridge - create bridge folder"
  file:
    path: "{{ bridge_path }}"
    state: directory

- name: "Bridge - download bridge binary"
  get_url:
    url: "{{ bridge_bin_url }}"
    checksum: "sha256:{{ bridge_bin_sha256 }}"
    dest: "{{ bridge_path }}/bridge"
    mode: "0755"
  notify:
    - restart {{ bridge_service_name }}

- name: "Bridge - create keystore folder"
  file:
    path: "{{ bridge_path }}/{{ bridge_keystore_folder }}"
    state: directory

# - name: "Bridge - create keystore files"
#   template:
#     src: "{{ item }}.j2"
#     dest: "{{ bridge_path }}/{{ bridge_keystore_folder }}/{{ item }}"
#   with_items:
#     - foreign-keystore.json
#     - home-keystore.json
#   notify:
#     - restart bridge

- name: "Bridge - create home keystore file"
  template:
    src: "home-keystore.json.j2"
    dest: "{{ bridge_path }}/{{ bridge_keystore_folder }}/home-keystore.json"
  notify:
    - restart bridge

- name: "Bridge - create foreign keystore file"
  template:
    src: "foreign-keystore.json.j2"
    dest: "{{ bridge_path }}/{{ bridge_keystore_folder }}/foreign-keystore.json"
  notify:
    - restart bridge
  when: home_signer_address != foreign_signer_address


- name: "Bridge - create password files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ bridge_path }}/{{ item }}"
  with_items:
    - foreign-password.txt
    - home-password.txt
  notify:
    - restart bridge

- name: "Bridge - create bridge config"
  template:
    src: config.toml.j2
    dest: "{{ bridge_path }}/config.toml"
  notify:
    - restart bridge

- name: "Bridge - create db.toml file from template"
  template:
    src: "db.toml.j2"
    dest: "{{ bridge_path }}/db.toml"
    force: no
  when: db_toml_location == ""

- name: "Bridge - copy db.toml file from local machine"
  copy:
    src: "{{ db_toml_location }}"
    dest: "{{ bridge_path }}/db.toml"
    force: no
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
  when: db_toml_location != ""

- name: "Bridge - install bridge service"
  become: yes
  become_user: root
  template:
    src: bridge.service.j2
    dest: /etc/systemd/system/{{ bridge_service_name }}.service
    owner: root
    group: root
  notify:
    - restart {{ bridge_service_name }}

- name: "Bridge - enable bridge service to start at boot"
  become: yes
  become_user: root
  command: "systemctl enable {{ bridge_service_name }}.service"

- name: "Bridge - ensure bridge service is running"
  become: yes
  become_user: root
  systemd:
    name: "{{ bridge_service_name }}.service"
    state: started
    enabled: yes
