---
- name: restart ufw
  become: yes
  become_user: root
  service:
    name: ufw
    state: restarted

- name: restart chrony
  become: yes
  become_user: root
  service:
    name: chrony
    state: restarted

- name: restart rsyslog
  become: true
  become_user: root
  service:
    name: rsyslog
    state: restarted
