---
- name: "Bridge - create bridge folder"
  file:
    path: "{{ bridge_path }}"
    state: directory

- name: "Bridge - download bridge binary"
  get_url:
    url: "{{ bridge_bin_url }}"
    checksum: "sha256:{{ bridge_bin_sha256 }}"
    dest: "{{ bridge_path }}/bridge"
    mode: "0755"
  notify:
    - restart {{ bridge_service_name }}

- name: "Bridge - create file with home contract bytecode"
  template:
    src: "HomeBridge.bin.j2"
    dest: "{{ bridge_path }}/HomeBridge.bin"

- name: "Bridge - create file with foreign contract bytecode"
  template:
    src: "ForeignBridge.bin.j2"
    dest: "{{ bridge_path }}/ForeignBridge.bin"

- name: "Bridge - create bridge config"
  template:
    src: config.toml.j2
    dest: "{{ bridge_path }}/config.toml"
  notify:
    - restart bridge

- name: "Bridge - create db.toml file from template"
  template:
    src: "db.toml.j2"
    dest: "{{ bridge_path }}/db.toml"
    force: no
  when: db_toml_location == ""

- name: "Bridge - copy db.toml file from local machine"
  copy:
    src: "{{ db_toml_location }}"
    dest: "{{ bridge_path }}/db.toml"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
  when: db_toml_location != ""

- name: "Bridge - install bridge service"
  become: yes
  become_user: root
  template:
    src: bridge.service.j2
    dest: /etc/systemd/system/{{ bridge_service_name }}.service
    owner: root
    group: root
    mode: "0755"
  notify:
    - restart {{ bridge_service_name }}

- name: "Bridge - wait for parity-home node to sync"
  uri:
    url: "http://localhost:{{ home_rpc_port }}"
    method: POST
    body_format: json
    return_content: yes
    body:
      jsonrpc: "2.0"
      method: "eth_syncing"
      params: []
      id: 1
  register: home_sync_status
  until: home_sync_status.json.result == False
  delay: 30
  retries: 120
  when: wait_sync

- name: "Bridge - wait for parity-foreign node to sync"
  uri:
    url: "http://localhost:{{ foreign_rpc_port }}"
    method: POST
    body_format: json
    return_content: yes
    body:
      jsonrpc: "2.0"
      method: "eth_syncing"
      params: []
      id: 1
  register: foreign_sync_status
  until: foreign_sync_status.json.result == False
  delay: 30
  retries: 120
  when: wait_sync

- name: "Bridge - enable bridge service to start at boot"
  become: yes
  become_user: root
  command: "systemctl enable {{ bridge_service_name }}.service"

- name: "Bridge - ensure bridge service is running"
  become: yes
  become_user: root
  systemd:
    name: "{{ bridge_service_name }}.service"
    state: started
    enabled: yes
  when: wait_sync
