- name: Slurp docker compose file
  slurp:
    src: "{{ bridge_path }}/docker-compose.yml"
  register: docker_compose_slurp

- name: Parse docker compose file
  set_fact: 
    docker_compose_parsed: "{{ docker_compose_slurp['content'] | b64decode | from_yaml }}"

- name: Set logger to remote server
  set_fact:
    docker_compose_parsed: "{{ docker_compose_parsed |combine({'services': {item: {'logging': {'driver': 'syslog','options': {'tag': '{{.Name}}/{{.ID}}'}}}}}, recursive=True) }}"
  with_items: "{{ docker_compose_parsed.services }}"
   
- name: Write new docker-compose file
  copy:
    content: "{{ docker_compose_parsed | to_nice_yaml }}"
    dest: "{{ bridge_path }}/docker-compose.yml"
