---
- name: Install nodejs
  include_role:
    name: nodejs

- name: Clone bridge_ui repo
  git:
    repo: "{{ bridge_ui_repo }}"
    version: "{{ bridge_ui_branch }}"
    dest: "{{ base_path }}/bridge-ui"

- name: Create helpers folder
  file:
    path: "{{ base_path }}/helpers/bridge-ui-env"
    state: directory

- name: Install npm package (toml)
  command: npm install toml
  args:
    chdir: "{{ base_path }}/helpers/bridge-ui-env"

- name: Create make-env.js script
  template:
    src: "make-env.js.j2"
    dest: "{{ base_path }}/helpers/bridge-ui-env/make-env.js"

- name: Create .env file
  command: "node make-env.js"
  args:
    chdir: "{{ base_path }}/helpers/bridge-ui-env/"

- name: Run npm install
  command: "npm install"
  args:
    chdir: "{{ base_path }}/bridge-ui"

- name: Run npm build
  command: "npm run build"
  args:
    chdir: "{{ base_path }}/bridge-ui"

- name: Install global npm package (http-server)
  become: true
  become_user: root
  command: npm install -g http-server

- name: Install global npm package (pm2)
  become: true
  become_user: root
  command: npm install -g pm2

# - name: Start bridge_ui
#   command: "pm2 start --name bridge-ui --interpreter http-server ."
#   args:
#     chdir: "{{ base_path }}/bridge-ui/build"

### install service
- name: Install bridge-ui service
  become: yes
  become_user: root
  template:
    src: bridge-ui.service.j2
    dest: /etc/systemd/system/bridge-ui.service
    owner: root
    group: root
    mode: "0755"

- name: Ensure bridge-ui is running and enabled to start at boot
  become: yes
  become_user: root
  service:
    name: bridge-ui
    state: started
    enabled: yes
