###### Accepts the following parametrs:
#
# bridge_path                             (*) path to the bridge folder (also used in templates)
# bridge_bin_url                          (*) url from which to download bridge binary
# bridge_bin_sha256                       (*) sha256 checksum of the binary
# bridge_service_name                     (*) name to be used for bridge service
# bridge_estimated_gas_cost_of_withdraw   bridge config option (used only in templates)
# bridge_deposit_relay_gas                bridge config option (used only in templates)
# bridge_withdraw_relay_gas               bridge config option (used only in templates)
# bridge_withdraw_confirm_gas             bridge config option (used only in templates)
# bridge_home_required_confirmations      bridge config option (used only in templates)
# bridge_home_poll_interval               bridge config option (used only in templates)
# bridge_home_request_timeout             bridge config option (used only in templates)
# bridge_foreign_required_confirmations   bridge config option (used only in templates)
# bridge_foreign_poll_interval            bridge config option (used only in templates)
# bridge_foreign_request_timeout          bridge config option (used only in templates)
# db_toml_location                        path to bridge db.toml **on local machine**
# restart_delay_sec                       (*) delay in seconds between restarts of brige service. Set to 0 to omit this option (used only in templates)
# wait_sync                               (*) yes/no - should playbook wait till parity nodes are synced before starting bridge service
#
---
bridge_path: "{{ base_path }}/bridge"
bridge_bin_url: "https://transfer.sh/Gh35m/bridge"
bridge_bin_sha256: "d1d8636652f1719a3d836eaaf3327eae25d7de43e40b8af887d5de5b0694b1f1"
bridge_service_name: "bridge"
db_toml_location: ""

bridge_home_contract_bytecode: ""
bridge_foreign_contract_bytecode: ""

restart_delay_sec: 3
wait_sync: yes
