---
- name: Bridge-ui - clone repo
  git:
    repo: "{{ bridge_ui_repo }}"
    version: "{{ bridge_ui_branch }}"
    dest: "{{ bridge_ui_path }}"

- name: Bridge-ui - run npm install
  command: "npm install"
  args:
    chdir: "{{ bridge_ui_path }}"

- name: Bridge-ui - create .env file
  template:
    src: env.j2
    dest: "{{ bridge_ui_path }}/.env"

- name: Bridge-ui - run npm build
  command: "npm run build"
  args:
    chdir: "{{ bridge_ui_path }}"

- name: Bridge-ui - install global npm package (http-server)
  become: true
  become_user: root
  command: npm install -g http-server

- name: Bridge-ui - install global npm package (pm2)
  become: true
  become_user: root
  command: npm install -g pm2

### install service
- name: Bridge-ui - install bridge-ui service
  become: yes
  become_user: root
  template:
    src: bridge-ui.service.j2
    dest: /etc/systemd/system/bridge-ui.service
    owner: root
    group: root
    mode: "0755"

- name: Bridge-ui - ensure bridge-ui is running and enabled to start at boot
  become: yes
  become_user: root
  service:
    name: bridge-ui
    state: started
    enabled: yes
