---
- name: Brdige-ui - install packages (apt)
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
  with_items:
    - gcc
    - g++
    - make

- name: Bridge-ui - install node-gyp (npm)
  become: yes
  become_user: root
  npm:
    name: node-gyp
    global: yes

- name: Bridge-ui - clone repo
  git:
    repo: "{{ bridge_ui_repo }}"
    version: "{{ bridge_ui_branch }}"
    dest: "{{ bridge_ui_path }}"

- name: Bridge-ui - run npm install
  npm:
    path: "{{ bridge_ui_path }}"

- name: Bridge-ui - create .env file
  template:
    src: env.j2
    dest: "{{ bridge_ui_path }}/.env"

- name: Bridge-ui - run npm build
  environment:
    PUBLIC_URL: "."
  command: "npm run build"
  args:
    chdir: "{{ bridge_ui_path }}"
  notify:
    - restart {{ bridge_ui_service_name }}

# - name: Bridge-ui - install global npm package (http-server)
#   become: yes
#   become_user: root
#   npm:
#     name: http-server
#     global: yes

- name: Bridge-ui - install pm2 (npm)
  become: yes
  become_user: root
  npm:
    name: pm2
    global: yes

### install service
- name: Bridge-ui - install bridge-ui service
  become: yes
  become_user: root
  template:
    src: bridge-ui.service.j2
    dest: "/etc/systemd/system/{{ bridge_ui_service_name }}.service"
    owner: root
    group: root
    mode: "0755"

- name: Bridge-ui - ensure bridge-ui is enabled to start at boot
  become: yes
  become_user: root
  command: "systemctl enable {{ bridge_ui_service_name }}.service"

- name: Bridge-ui - ensure bridge-ui is running
  become: yes
  become_user: root
  systemd:
    name: "{{ bridge_ui_service_name }}.service"
    state: started
    enabled: yes
